show different forms for developer and product team
buildly-release-management/buildly-react-template pull request #69
Opened 2022-02-03 11:27 UTC by MounikaReddy15

## Purpose
_Redirect users based on whether they are developer or product team during user registration_

## Further info
_showing survey for developer and new product form for product team_

## Ticket number
#66

2022-02-03 11:38 UTC, RadhikaPPatel requested changes
Please handle the requested changes

2022-02-03 11:38 UTC, RadhikaPPatel commented on src/pages/Register/Register.js
> +                <Grid container spacing={isMobile() ? 0 : 3}>
Why is this autocomplete field? It needs to be a normal select field only.

2022-02-03 11:38 UTC, RadhikaPPatel commented on src/pages/Dashboard/components/UserDashboard.js
> +        {/* <Grid item xs={4} md={3} lg={2} textAlign="end">
Why is this hidden?

2022-02-03 11:38 UTC, RadhikaPPatel commented on src/pages/Register/Register.js
> +                <Grid container spacing={isMobile() ? 0 : 3}>
Also, fix all the problems for this file.

2022-02-08 10:19 UTC, yasmin2496 requested changes
@MounikaReddy15 Two things to check
1. For developers, after filling the survey it takes them back to the form page and the form is still visible. Ideally, this should hide once the form is filled
2. For product team, after successful filling up of form it stays on modal take the user to dashboard and close the modal. Also the alert message is incorrect

2022-02-08 10:20 UTC, yasmin2496 commented
@MounikaReddy15 There is also some problem with product modal now. After clicking on create product I can't close the modal being sure that my changes are saved. Check this as well

2022-02-09 10:31 UTC, yasmin2496 approved these changes

2022-02-09 10:35 UTC, merged