Feat#63/test feat issue crud
buildly-release-management/buildly-react-template pull request #84
Opened 2022-03-01 14:22 UTC by MounikaReddy15

## Purpose
_Fetch credentials for creating feature/issue on third party tools_

## Further info
_All crud operations are working on insights, trello & github_

## Ticket number
#82

2022-03-02 11:12 UTC, RadhikaPPatel requested changes

2022-03-02 11:12 UTC, RadhikaPPatel commented on src/pages/Dashboard/components/UserDashboard.js
> +    const cred = _.filter(
This code can be shortened. Use find instead of filter and user spread operator instead of single value updates.

2022-03-02 11:12 UTC, RadhikaPPatel commented on src/pages/Dashboard/forms/AddFeatures.js
> +    const featCred = _.filter(
Use find instead of a filter.

2022-03-02 11:12 UTC, RadhikaPPatel commented on src/pages/Dashboard/forms/AddFeatures.js
> +      tool_name: featCred[0]?.auth_detail.tool_name,
Use spread operator instead of single value updates.

2022-03-02 11:12 UTC, RadhikaPPatel commented on src/pages/Dashboard/forms/AddFeatures.js
> +              && product.feature_tool_detail.organisation_list[0].board_list[0].column_list
Do not use first organization by default. Use should be able to select any column for any board from any organization.

2022-03-02 11:12 UTC, RadhikaPPatel commented on src/pages/Dashboard/forms/AddIssues.js
> +    const issueCred = _.filter(
Use find instead of filter

2022-03-02 11:12 UTC, RadhikaPPatel commented on src/pages/Dashboard/forms/AddIssues.js
> +      tool_name: issueCred[0]?.auth_detail.tool_name,
Use spread operator instead of single values

2022-03-02 11:12 UTC, RadhikaPPatel commented on src/pages/Dashboard/forms/AddIssues.js
> +                      {_.map(product.issue_tool_detail.organisation_list[0].repo_list, (repos, repoIdx) => (
Do not use first organization by default. Users should be able to select any repo from any organization.

2022-03-02 11:12 UTC, RadhikaPPatel commented on src/pages/Dashboard/forms/AddIssues.js
> +  const [product, setProduct] = useState('');
Why do we need this use state? Do we not pass the product already here?

2022-03-02 11:12 UTC, RadhikaPPatel commented on src/redux/product/sagas/product.saga.js
> +      `${window.env.API_URL}${productEndpoint}credential/?product_uuid=${payload.credential_uuid.credential_uuid}`,
Why is there a product_uuid query parameter for normal GET call in credentials? Also why credentials are passed as product_uuid?

2022-03-23 06:16 UTC, MounikaReddy15 commented
changes are present in another pr #86

2022-03-23 06:16 UTC, closed without merging