Feat#82/fetch credentials to do crud on third party tools
buildly-release-management/buildly-react-template pull request #86
Opened 2022-03-07 11:55 UTC by MounikaReddy15

## Purpose
_Fetch credentials to do crud on third party tools_

## Further info
_All crud operations are working on insights, trello & github_

## Ticket number
#82

2022-03-21 08:35 UTC, RadhikaPPatel requested changes
Please cross-check all changes once again as well as retest with dev BE once.

2022-03-21 08:35 UTC, RadhikaPPatel commented on src/App.js
> +          <Route path={routes.MISSING_DATA} component={MissingData} />
Why is this page moved here? Anything that needs to be accessed post-login needs to be in Container. Anything that needs to be accessed without login will be in App.

2022-03-21 08:35 UTC, RadhikaPPatel commented on src/layout/TopBar/TopBar.js
> -  useEffect(() => {
I guess you will need this back as well.

2022-03-21 08:35 UTC, RadhikaPPatel commented on src/pages/Dashboard/components/UserDashboard.js
> +  }, [product, features, issues, features.length, issues.length]);
Remove these from here. Do not length check in useEffect run condition. Instead use it inside useEffect.

2022-03-21 08:35 UTC, RadhikaPPatel commented on src/pages/Dashboard/components/UserDashboard.js
> +      const featCred = _.find(
Why do we need to fetch the creds here again? Can't we just pass it in the callback?

2022-03-30 15:04 UTC, yasmin2496 commented
Unable to convert to issue and create new issue as well. Please check @MounikaReddy15 @mthombare . Returns 400
![image](https://user-images.githubusercontent.com/61192422/160866743-9ed22d5d-fabe-4650-91a5-021860685ca2.png)

2022-03-30 15:05 UTC, yasmin2496 requested changes
Issue creation is not working

2022-03-31 05:42 UTC, MounikaReddy15 commented
> Issue creation is not working

@yasmin2496 I checked every CRUD is working fine

2022-04-07 07:50 UTC, yasmin2496 requested changes
1. Can the Kanban view have less padding space. Instead of using padding as 16px could you check with 8px. Right now, it looks like there is good amount of empty space left
2. In Kanban view, if you move the card in any of the columns it is not reflected on the source 
3. For issue, update made to Organization is not retained. It clears out everytime issue details is opened

2022-04-07 10:18 UTC, yasmin2496 approved these changes
Suggestions going in ticket - https://github.com/buildly-release-management/buildly-react-template/issues/89

2022-04-07 11:36 UTC, RadhikaPPatel requested changes
Requested changes for below

1. Feature not being created on GitHub Project board. Is it FE or BE issue?
2. If we change the Feature Status say from Backlog to In Progress, how does it move the corresponding cards in Trello or GitHub to the correct columns/swimlanes?

2022-04-08 06:05 UTC, RadhikaPPatel approved these changes
2 points notified will be covered in a separate PR

2022-04-08 11:25 UTC, yasmin2496 approved these changes
Looks good

2022-04-08 11:26 UTC, merged